# Generated by Django 3.0.2 on 2020-01-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Item ready to purchase'), ('SOLD', 'Item sold'),
                                                     ('Restocking', 'Item will be restocked soon')], default='SOLD',
                                            max_length=10)),
                ('issues', models.CharField(default='No Isssues', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Item ready to purchase'), ('SOLD', 'Item sold'),
                                                     ('Restocking', 'Item will be restocked soon')], default='SOLD',
                                            max_length=10)),
                ('issues', models.CharField(default='No Isssues', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Item ready to purchase'), ('SOLD', 'Item sold'),
                                                     ('Restocking', 'Item will be restocked soon')], default='SOLD',
                                            max_length=10)),
                ('issues', models.CharField(default='No Isssues', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
